[build]
  command = "pnpm run build"
  publish = ".next"

[[redirects]]
  from = "/script.js"
  to = "https://endpoint-b.longlive.cloud/script.js"
  status = 200
  force = true
  headers = { Cache-Control = "public, max-age=600" }

[[redirects]]
  from = "/api/event"
  to = "https://endpoint-b.longlive.cloud/api/event"
  status = 200
  force = true

[[headers]]
  for = "/logos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=2592000"

[[headers]]
  for = "/og-image.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=2592000"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=2592000"

[[headers]]
  for = "/favicon.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=2592000"
