export type PlanCategory = "国内大厂" | "其他"

export type Plan = {
  id: string
  company: string
  product: string
  category: PlanCategory
  links: {
    official: string
    affiliate?: string
  }
  logo?: {
    src: string
    alt: string
  }
  models: string[]
  tiers: Tier[]
  billingUnit: "API请求" | "请求次数" | "按量计费" | "积分制" | "Token计费"
  tools: string[]
  toolCount: number
  tags: string[]
  /** 重要说明（展示在卡片内，如停售公告） */
  notice?: string
  yearlyPrice?: number      // 年付价格 (e.g., Kimi ¥468/年)
  quarterlyPrice?: number   // 季付价格
}

export type Tier = {
  name: string
  price: number
  firstMonthPrice?: number
  secondMonthPrice?: number  // 次月价格 (e.g., 次月半价)
  /** 包 = 一次性按量包（非连续月付） */
  period: "月" | "季" | "年" | "包"
  limit5h: string
  limitWeek?: string
  limitMonth?: string
  limit5hCount?: number      // 结构化：5小时配额（次）
  limitWeekCount?: number    // 结构化：7天配额（次）
  limitMonthCount?: number   // 结构化：30天配额（次）
  isFirstMonthOnly?: boolean // 新人专享一次性，不计入最低月付
  /** 已停止接受新购（仍展示供参考，UI 删除线） */
  discontinuedForNewSales?: boolean
  notes?: string
}

/** 参与比价、卡片主价格的常规档位（排除停售新购；若全部停售则回退为全部常规档） */
export function purchasableRegularTiers(plan: Plan): Tier[] {
  const regular = plan.tiers.filter((t) => !t.isFirstMonthOnly)
  const active = regular.filter((t) => !t.discontinuedForNewSales)
  return active.length ? active : regular
}

/** 全套餐（含新人专享）中最低首月价；不停售档才计入 */
export function lowestFirstMonthInPlan(plan: Plan): number | undefined {
  let best: number | undefined
  for (const t of plan.tiers) {
    if (t.discontinuedForNewSales) continue
    if (t.firstMonthPrice === undefined) continue
    if (best === undefined || t.firstMonthPrice < best) best = t.firstMonthPrice
  }
  return best
}

/** 用于排序、入门价等：按量包按标价比较；月季年按折算月价 */
export function tierComparableMonthly(t: Tier): number {
  if (t.period === "季") return Math.round(t.price / 3)
  if (t.period === "年") return Math.round(t.price / 12)
  return t.price
}

export const plans: Plan[] = [
  {
    id: "bailian",
    company: "阿里云",
    product: "百炼 Coding Plan",
    category: "国内大厂",
    links: {
      official: "https://www.aliyun.com/benefit/scene/codingplan",
      affiliate: "https://www.aliyun.com/benefit/scene/codingplan?source=5176.29345612&userCode=y44p2mtf",
    },
    logo: { src: "/logos/qwen.png", alt: "通义千问" },
    notice:
      "公告时间 2026-04-11：因产品策略调整，百炼 Coding Plan Lite 将于北京时间 2026-04-13 18:00 起停止续费和升级。已购用户可继续使用至到期；已开通自动续费的 Lite 将于公告 30 日后自动失效，不影响当前有效期内使用。",
    models: [
      "qwen3.6-plus",
      "kimi-k2.5",
      "glm-5",
      "MiniMax-M2.5",
      "qwen3.5-plus",
      "qwen3-max-2026-01-23",
      "qwen3-coder-next",
      "qwen3-coder-plus",
      "glm-4.7",
    ],
    tiers: [
      {
        name: "Pro",
        price: 200,
        period: "月",
        limit5h: "6,000 次",
        limitWeek: "45,000 次",
        limitMonth: "90,000 次",
        limit5hCount: 6000,
        limitWeekCount: 45000,
        limitMonthCount: 90000,
        notes: "高级套餐：复杂项目及大规模开发任务；推荐模型含 qwen3.6-plus、kimi-k2.5、glm-5、MiniMax-M2.5",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "Cline", "OpenClaw", "Qwen Code"],
    toolCount: 4,
    tags: ["多模型", "固定月费", "Lite停止续费升级"],
  },
  {
    id: "bailian-token-team",
    company: "阿里云",
    product: "百炼 Token Plan",
    category: "国内大厂",
    links: {
      official: "https://cn.aliyun.com/benefit/scene/tokenplan",
    },
    logo: { src: "/logos/qwen.png", alt: "通义千问" },
    notice:
      "更新时间：2026-05-01。Token Plan 团队版目前仅支持华北2（北京）地域；以 Credits 统一计量，支持文本与图像生成模型。",
    models: [
      "qwen3.6-plus",
      "glm-5",
      "MiniMax-M2.5",
      "DeepSeek-V3.2",
      "qwen-image-2.0",
      "qwen-image-2.0-pro",
      "wan2.7-image",
      "wan2.7-image-pro",
    ],
    tiers: [
      {
        name: "标准坐席",
        price: 198,
        period: "月",
        limit5h: "-",
        limitMonth: "25,000积分",
        notes: "轻度使用 AI 辅助的团队成员",
      },
      {
        name: "高级坐席",
        price: 698,
        period: "月",
        limit5h: "-",
        limitMonth: "100,000积分",
        notes: "日常高频使用 AI 编码的团队成员",
      },
      {
        name: "尊享坐席",
        price: 1398,
        period: "月",
        limit5h: "-",
        limitMonth: "250,000积分",
        notes: "重度依赖 AI 编码的核心开发者",
      },
      {
        name: "共享用量包",
        price: 5000,
        period: "包",
        limit5h: "-",
        limitMonth: "625,000积分（有效期1个月）",
        notes: "跨坐席共享，坐席额度用尽后抵扣；多个用量包按最近到期优先抵扣",
      },
    ],
    billingUnit: "Token计费",
    tools: ["OpenClaw", "Hermes Agent", "Qwen Code", "Qoder", "Claude Code", "OpenCode"],
    toolCount: 6,
    tags: ["Credits计量", "文本+图像模型", "团队版", "多坐席"],
  },
  {
    id: "ark",
    company: "字节跳动",
    product: "火山方舟 Coding Plan",
    category: "国内大厂",
    links: {
      official: "https://www.volcengine.com/activity/codingplan",
      affiliate: "https://volcengine.com/L/htePBo7G28s/",
    },
    logo: { src: "/logos/volcengine.png", alt: "火山引擎" },
    notice: "火山方舟 Coding Plan 当前库存售罄；新购建议查看火山方舟 Agent Plan。",
    models: ["Doubao-Seed-2.0-Code", "Doubao-Seed-Code", "Kimi-K2.5", "Kimi-K2", "GLM-4.7", "DeepSeek-V3.2"],
    tiers: [
      {
        name: "Lite",
        price: 40,
        period: "月",
        limit5h: "~1,200 次",
        limitWeek: "9,000 次",
        limitMonth: "18,000 次",
        limit5hCount: 1200,
        limitWeekCount: 9000,
        limitMonthCount: 18000,
        notes: "新用户首购每日10:30限量开放；邀请码 RZ3TQMRE",
      },
      {
        name: "Pro",
        price: 200,
        period: "月",
        limit5h: "~6,000 次",
        limitWeek: "45,000 次",
        limitMonth: "90,000 次",
        limit5hCount: 6000,
        limitWeekCount: 45000,
        limitMonthCount: 90000,
        notes: "支持Auto模式智能调度；邀请码 RZ3TQMRE",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "Cursor", "Cline", "Codex CLI", "Kilo Code", "Roo Code", "OpenCode", "Moltbot"],
    toolCount: 11,
    tags: ["多模型", "Auto模式", "库存售罄"],
  },
  {
    id: "ark-agent",
    company: "字节跳动",
    product: "火山方舟 Agent Plan",
    category: "国内大厂",
    links: {
      official: "https://www.volcengine.com/activity/agentplan",
    },
    logo: { src: "/logos/volcengine.png", alt: "火山引擎" },
    notice:
      "方舟 Agent Plan 面向个人用户，采用 Agent 燃料值（AFP）统一计量；文本/向量/视频按原始 token 抵扣，图片按张抵扣。套餐额度仅在 AI 工具中生效，不可用于普通 API 调用；误用普通 API 可能导致订阅停用或账号封禁。",
    models: [
      "doubao-seed-2.0-mini",
      "doubao-seed-2.0-lite",
      "doubao-seed-2.0-code",
      "doubao-seed-2.0-pro",
      "deepseek-v3.2",
      "minimax-m2.7",
      "glm-5.1",
      "kimi-k2.6",
      "doubao-embedding-vision",
      "doubao-seedream-5.0-lite",
      "doubao-seedance-1.5-pro",
      "doubao-seedance-2.0",
      "doubao-seedance-2.0-fast",
      "联网搜索 Harness",
    ],
    tiers: [
      {
        name: "Small",
        price: 40,
        period: "月",
        limit5h: "2,000 AFP",
        limitWeek: "7,000 AFP",
        limitMonth: "20,000 AFP",
        notes: "支持文本/向量/图片，不含视频生成；视觉模型日额度 10,000 AFP；联网搜索每月 50 次免费额度",
      },
      {
        name: "Medium",
        price: 200,
        period: "月",
        limit5h: "10,000 AFP",
        limitWeek: "35,000 AFP",
        limitMonth: "100,000 AFP",
        notes: "支持视频生成；视觉模型日额度 50,000 AFP；联网搜索每月 150 次免费额度",
      },
      {
        name: "Large",
        price: 500,
        period: "月",
        limit5h: "25,000 AFP",
        limitWeek: "87,500 AFP",
        limitMonth: "250,000 AFP",
        notes: "支持视频生成；视觉模型日额度 125,000 AFP；联网搜索每月 400 次免费额度",
      },
      {
        name: "Max",
        price: 1000,
        period: "月",
        limit5h: "50,000 AFP",
        limitWeek: "175,000 AFP",
        limitMonth: "500,000 AFP",
        notes: "支持视频生成；视觉模型日额度 250,000 AFP；联网搜索每月 800 次免费额度",
      },
    ],
    billingUnit: "积分制",
    tools: ["Claude Code", "OpenCode", "OpenClaw", "Hermes Agent", "Roo Code", "Cline", "Kilo Code", "Cursor"],
    toolCount: 8,
    tags: ["Agent Plan", "AFP积分", "全模态", "联网搜索"],
  },
  {
    id: "huawei",
    company: "华为云",
    product: "CodeArts 码道",
    category: "国内大厂",
    links: { official: "https://www.huaweicloud.com/product/codearts/ai.html" },
    logo: { src: "/logos/huawei.png", alt: "华为云" },
    models: ["盘古", "多模型接入"],
    tiers: [
      {
        name: "个人版（公测）",
        price: 0,
        period: "月",
        limit5h: "公测免费",
        notes: "公测版临时免费（后续可能调整）",
      },
    ],
    billingUnit: "积分制",
    tools: ["CodeArts IDE", "VS Code", "主流开发工具"],
    toolCount: 5,
    tags: ["公测免费", "临时", "码道", "盘古"],
  },
  {
    id: "glm",
    company: "智谱AI",
    product: "GLM Coding Plan",
    category: "其他",
    links: {
      official: "https://www.bigmodel.cn/glm-coding",
      affiliate: "https://www.bigmodel.cn/glm-coding?ic=R8RQ6LQCRJ",
    },
    logo: { src: "/logos/bigmodel.png", alt: "智谱AI" },
    models: ["GLM-5.1", "GLM-5-Turbo", "GLM-4.7", "GLM-4.6", "GLM-4.5-Air", "GLM-5（Max/Pro）"],
    tiers: [
      {
        name: "Lite",
        price: 49,
        period: "月",
        limit5h: "~80 次对话",
        limitWeek: "~400 次对话",
        notes: "MCP 100次/月；基础模型全支持",
      },
      {
        name: "Pro",
        price: 149,
        period: "月",
        limit5h: "~400 次对话",
        limitWeek: "~2,000 次对话",
        notes: "MCP 1,000次/月；含 GLM-5",
      },
      {
        name: "Max",
        price: 469,
        period: "月",
        limit5h: "~1,600 次对话",
        limitWeek: "~8,000 次对话",
        notes: "MCP 4,000次/月，高峰优先；含 GLM-5",
      },
    ],
    billingUnit: "请求次数",
    tools: ["Claude Code", "Roo Code", "Kilo Code", "Cline", "OpenCode", "Cursor", "CodeGeeX"],
    toolCount: 20,
    tags: ["自研模型", "MCP工具"],
    yearlyPrice: 411,  // Lite年费 ¥411 (7折)
    quarterlyPrice: 132, // Lite季费 ¥132 (9折)
  },
  {
    id: "kimi",
    company: "月之暗面",
    product: "Kimi Code Plan",
    category: "其他",
    links: { official: "https://www.kimi.com/membership/pricing" },
    logo: { src: "/logos/kimi.png", alt: "Kimi" },
    models: ["Kimi K2.6", "Kimi K2.5", "Kimi K2 Thinking"],
    tiers: [
      {
        name: "Andante",
        price: 49,
        period: "月",
        limit5h: "300–1,200 次",
        limitMonth: "~17M token",
        notes: "基础使用：含 Deep Research、网页部署、专业数据与 Kimi Code",
      },
      {
        name: "Moderato",
        price: 99,
        period: "月",
        limit5h: "1,200–4,800 次",
        limitMonth: "~69M token",
        notes: "进阶效率：2x Agent 积分 + Kimi Code 4x 配额，多设备登录",
      },
      {
        name: "Allegretto",
        price: 199,
        period: "月",
        limit5h: "6,000–24,000 次",
        limitMonth: "~343M token",
        notes: "专业创作：4x Agent 积分，支持多任务、Kimi Claw 与 Agent Swarm",
      },
      {
        name: "Allegro",
        price: 699,
        period: "月",
        limit5h: "18,000–72,000 次",
        limitMonth: "~1B token",
        notes: "旗舰模式：10x Agent 积分 + Kimi Code 60x，含 Claw 与 Agent Swarm",
      },
    ],
    billingUnit: "Token计费",
    tools: ["Kimi Code CLI", "Kimi Code for VS Code", "Claude Code", "Roo Code"],
    toolCount: 4,
    tags: ["K2.6 / K2.5", "7天滚动刷新", "256K上下文"],
    yearlyPrice: 468,
  },
  {
    id: "xfyun",
    company: "科大讯飞",
    product: "讯飞星辰 Astron Coding Plan",
    category: "其他",
    links: {
      official: "https://training.xfyun.cn/modelSquare",
      affiliate: "https://training.xfyun.cn/packageSubscription?inviteCode=MAAS-23F9F34A",
    },
    logo: { src: "/logos/xfyun.png", alt: "讯飞星辰" },
    models: [
      "Qwen3.5-35B-A3B",
      "Qwen3-Coder-Next-FP8",
      "GLM-4.7-Flash",
      "Spark X2",
      "GLM-5",
      "GLM-5.1",
      "MiniMax-M2.5",
      "Kimi-K2.5",
      "DeepSeek-V3.2",
      "Qwen3.5-397B-A17B",
    ],
    tiers: [
      {
        name: "无忧版",
        price: 19,
        firstMonthPrice: 3.9,
        secondMonthPrice: 19,
        period: "月",
        limit5h: "不限",
        notes: "首购优惠价 ¥3.90/月，后续恢复原价；支持 Qwen3.5-35B-A3B / Qwen3-Coder-Next-FP8 / GLM-4.7-Flash",
      },
      {
        name: "专业版",
        price: 39,
        period: "月",
        limit5h: "1,200 次请求",
        limitWeek: "9,000 次请求",
        limitMonth: "18,000 次请求",
        limit5hCount: 1200,
        limitWeekCount: 9000,
        limitMonthCount: 18000,
        notes:
          "支持 Spark X2 / GLM-5 / MiniMax-M2.5 / Kimi-K2.5 / DeepSeek-V3.2 / GLM-4.7-Flash / Qwen3.5-35B-A3B / Qwen3-Coder-Next-FP8 / Qwen3.5-397B-A17B",
      },
      {
        name: "高效版",
        price: 199,
        period: "月",
        limit5h: "6,000 次请求",
        limitWeek: "45,000 次请求",
        limitMonth: "90,000 次请求",
        limit5hCount: 6000,
        limitWeekCount: 45000,
        limitMonthCount: 90000,
        notes:
          "支持 Spark X2 / GLM-5 / GLM-5.1 / MiniMax-M2.5 / Kimi-K2.5 / DeepSeek-V3.2 / GLM-4.7-Flash / Qwen3.5-35B-A3B / Qwen3-Coder-Next-FP8 / Qwen3.5-397B-A17B",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "Cline", "Cursor", "OpenClaw"],
    toolCount: 4,
    tags: ["首购特惠", "请求次数", "多模型"],
  },
  {
    id: "xiaomi-mimo",
    company: "小米",
    product: "MiMo Token Plan",
    category: "国内大厂",
    links: {
      official: "https://platform.xiaomimimo.com/token-plan",
      affiliate: "https://platform.xiaomimimo.com?ref=SRTY5N",
    },
    logo: { src: "/logos/xiaomi.png", alt: "小米" },
    notice:
      "限时活动（2026-04-28 至 2026-05-28）：Xiaomi MiMo Orbit 百万亿 Token 发放进行中，可在 https://100t.xiaomimimo.com/ 申请，最高可领 2亿～16亿额度 / $300 Credit（以审核到账为准）。",
    models: [
      "MiMo-V2.5-Pro",
      "MiMo-V2.5",
      "MiMo-V2.5-TTS-VoiceClone",
      "MiMo-V2.5-TTS-VoiceDesign",
      "MiMo-V2.5-TTS",
      "MiMo-V2-Pro",
      "MiMo-V2-Omni",
      "MiMo-V2-TTS",
    ],
    tiers: [
      {
        name: "Lite",
        price: 39,
        firstMonthPrice: 34.3,
        period: "月",
        limit5h: "-",
        limitMonth: "60M 积分",
        notes: "约120轮（V2.5/Omni）；$6/月；年¥411.84·720M",
      },
      {
        name: "Standard",
        price: 99,
        firstMonthPrice: 87.1,
        period: "月",
        limit5h: "-",
        limitMonth: "200M 积分",
        notes: "约400轮；$16/月；年¥1045·2400M",
      },
      {
        name: "Pro",
        price: 329,
        firstMonthPrice: 289.5,
        period: "月",
        limit5h: "-",
        limitMonth: "700M 积分",
        notes: "约1400轮；$50/月；年¥3474·8400M",
      },
      {
        name: "Max",
        price: 659,
        firstMonthPrice: 579.9,
        period: "月",
        limit5h: "-",
        limitMonth: "1600M 积分",
        notes: "约3200轮；$100/月；年¥6959·19200M",
      },
    ],
    billingUnit: "积分制",
    tools: ["Claude Code", "OpenClaw", "OpenCode", "Kilo Code", "Cline"],
    toolCount: 5,
    tags: ["8 旗舰模型", "四档梯度", "夜间0.8×", "首购88折", "编程工具专用"],
  },
  {
    id: "minimax",
    company: "MiniMax",
    product: "MiniMax Token Plan",
    category: "其他",
    links: {
      official: "https://platform.minimaxi.com/subscribe/token-plan",
      affiliate: "https://platform.minimaxi.com/subscribe/token-plan?code=uQkm#YTxQ#SGio4O&source=link",
    },
    logo: { src: "/logos/minimax.png", alt: "MiniMax" },
    models: ["MiniMax-M2.7", "MiniMax-M2.7-highspeed", "MiniMax-M2.5", "MiniMax-M2.1", "MiniMax-M2"],
    tiers: [
      {
        name: "Starter",
        price: 29,
        period: "月",
        limit5h: "600 次对话",
        limit5hCount: 600,
        notes: "年付¥290（省2月）",
      },
      {
        name: "Plus",
        price: 49,
        period: "月",
        limit5h: "1,500 次对话",
        limit5hCount: 1500,
        notes: "年付¥490（省2月）",
      },
      {
        name: "Max",
        price: 119,
        period: "月",
        limit5h: "4,500 次对话",
        limit5hCount: 4500,
        notes: "年付¥1,190（省2月）",
      },
      {
        name: "Plus-极速版",
        price: 98,
        period: "月",
        limit5h: "1,500 次对话",
        limit5hCount: 1500,
        notes: "M2.7-highspeed；年付¥980（省2月）",
      },
      {
        name: "Max-极速版",
        price: 199,
        period: "月",
        limit5h: "4,500 次对话",
        limit5hCount: 4500,
        notes: "M2.7-highspeed；年付¥1,990（省2月）",
      },
      {
        name: "Ultra-极速版",
        price: 899,
        period: "月",
        limit5h: "30,000 次对话",
        limit5hCount: 30000,
        notes: "M2.7-highspeed；年付¥8,990（省2月）",
      },
    ],
    billingUnit: "请求次数",
    tools: ["Claude Code", "Roo Code", "Kilo Code", "Cline", "Codex CLI", "OpenCode", "Droid", "TRAE", "Grok CLI", "Cursor"],
    toolCount: 10,
    tags: ["Token Plan", "M2.7", "100+ TPS"],
  },
  {
    id: "infini",
    company: "无问芯穹",
    product: "Infini Coding Plan",
    category: "其他",
    links: {
      official: "https://cloud.infini-ai.com/platform/ai",
      affiliate: "https://cloud.infini-ai.com/login?redirect=/genstudio/invitation&invite_code=BewkvUYk",
    },
    logo: { src: "/logos/infini.png", alt: "无问芯穹" },
    models: ["DeepSeek-V3.2", "DeepSeek-V3.2-Thinking", "Kimi-2.5", "MiniMax-M2.1", "MiniMax-M2.5", "GLM-4.7", "GLM-5"],
    tiers: [
      {
        name: "Lite",
        price: 40,
        firstMonthPrice: 19.9,
        secondMonthPrice: 40,
        period: "月",
        limit5h: "1,000 次",
        limitMonth: "12,000 次",
        limit5hCount: 1000,
        limitWeekCount: 6000,
        limitMonthCount: 12000,
        notes: "首次首月5折；邀请码 BewkvUYk",
      },
      {
        name: "Pro",
        price: 200,
        firstMonthPrice: 99.9,
        secondMonthPrice: 200,
        period: "月",
        limit5h: "5,000 次",
        limitMonth: "60,000 次",
        limit5hCount: 5000,
        limitWeekCount: 30000,
        limitMonthCount: 60000,
        notes: "首次首月5折；邀请码 BewkvUYk",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "Cursor", "Roo Code", "Cline", "VS Code 插件"],
    toolCount: 5,
    tags: ["多模型", "滑动窗口"],
  },
  {
    id: "tencent",
    company: "腾讯云",
    product: "Hy Token Plan",
    category: "国内大厂",
    links: {
      official: "https://cloud.tencent.com/act/pro/tokenplan",
      affiliate: "https://cloud.tencent.com/act/cps/redirect?redirect=38205&cps_key=b1b782d9eb899c792b44ce3dccf79759",
    },
    logo: { src: "/logos/tencentcloud.png", alt: "腾讯云" },
    notice:
      "Hy Token Plan 限时优惠：Lite 和 Standard 套餐享 5 折优惠，活动时间 2026.04.30-05.06，限购 1 个，以官网活动规则为准。",
    models: [
      "GLM-5.1",
      "GLM-5",
      "kimi-k2.5",
      "MiniMax-M2.7",
      "MiniMax-M2.5",
      "Tencent HY 2.0 Think",
      "Tencent HY 2.0 Instruct",
    ],
    tiers: [
      {
        name: "Lite - 体验套餐",
        price: 28,
        firstMonthPrice: 14,
        secondMonthPrice: 28,
        period: "月",
        limit5h: "-",
        limitMonth: "3500 万 Tokens",
        notes: "Hy 个人版体验套餐；0.4元/百万tokens；约 70 轮问答；限时 5 折活动价 14 元（2026.04.30-05.06，限 1 个）",
      },
      {
        name: "Standard - 基础套餐",
        price: 78,
        firstMonthPrice: 39,
        secondMonthPrice: 78,
        period: "月",
        limit5h: "-",
        limitMonth: "1 亿 Tokens",
        notes: "Hy 个人版基础套餐；0.39元/百万tokens；约 200 轮问答；限时 5 折活动价 39 元（2026.04.30-05.06，限 1 个）",
      },
      {
        name: "Pro - 进阶套餐",
        price: 238,
        period: "月",
        limit5h: "-",
        limitMonth: "3.2 亿 Tokens",
        notes: "Hy 个人版进阶套餐；适合每天高频使用 AI 的开发者和效率达人",
      },
      {
        name: "Max - 专业套餐",
        price: 468,
        period: "月",
        limit5h: "-",
        limitMonth: "6.5 亿 Tokens",
        notes: "Hy 个人版专业套餐；适合把 AI 当核心生产力工具的重度用户",
      },
    ],
    billingUnit: "Token计费",
    tools: [
      "OpenClaw",
      "CodeBuddy Code",
      "OpenCode",
      "Claude Code",
      "Codex",
      "Cline",
      "Cursor",
      "Kilo CLI",
      "Kilo Code",
    ],
    toolCount: 9,
    tags: ["Hy Token Plan", "Hy3 preview", "限时5折", "混元模型"],
  },
  {
    id: "jdcloud",
    company: "京东云",
    product: "京东云 Coding Plan",
    category: "其他",
    links: { official: "https://www.jdcloud.com/cn/pages/codingplan" },
    logo: { src: "/logos/jd.png", alt: "京东" },
    models: [
      "DeepSeek-V3.2",
      "GLM-5",
      "GLM-4.7",
      "MiniMax-M2.5",
      "Kimi-K2.5",
      "Kimi-K2-Turbo",
      "Qwen3-Coder",
    ],
    tiers: [
      {
        name: "Lite",
        price: 40,
        firstMonthPrice: 19.9,
        period: "月",
        limit5h: "~1,200 次",
        limitWeek: "~9,000 次",
        limitMonth: "~18,000 次",
        limit5hCount: 1200,
        limitWeekCount: 9000,
        limitMonthCount: 18000,
        notes:
          "每天10:30限量开抢，每月最多18,000次请求；每次提问可能触发多次模型调用，实际消耗与项目复杂度/是否开启深度思考有关（以控制台为准）",
      },
      {
        name: "Pro",
        price: 200,
        firstMonthPrice: 99.9,
        period: "月",
        limit5h: "~6,000 次",
        limitWeek: "~45,000 次",
        limitMonth: "~90,000 次",
        limit5hCount: 6000,
        limitWeekCount: 45000,
        limitMonthCount: 90000,
        notes: "Lite 用量的 5 倍；每天10:30限量开抢（以控制台活动页面为准）",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "OpenCode", "OpenClaw", "Roo Code", "Cursor"],
    toolCount: 5,
    tags: ["多模型", "工具共享额度", "首月优惠"],
  },
  {
    id: "baidu",
    company: "百度",
    product: "千帆 Coding Plan",
    category: "国内大厂",
    links: { official: "https://cloud.baidu.com/product/codingplan.html" },
    logo: { src: "/logos/yiyan.png", alt: "文心一言" },
    models: ["DeepSeek-V3.2", "GLM-4.7", "GLM-5", "Kimi-K2.5", "MiniMax-M2.1", "MiniMax-M2.5"],
    tiers: [
      {
        name: "Lite",
        price: 40,
        firstMonthPrice: 7.9,
        secondMonthPrice: 20,
        period: "月",
        limit5h: "1,200 次",
        limitWeek: "9,000 次",
        limitMonth: "18,000 次",
        limit5hCount: 1200,
        limitWeekCount: 9000,
        limitMonthCount: 18000,
        notes: "第三月起¥40/月, 控制台一键切换模型",
      },
      {
        name: "Pro",
        price: 200,
        firstMonthPrice: 39.9,
        secondMonthPrice: 100,
        period: "月",
        limit5h: "6,000 次",
        limitWeek: "45,000 次",
        limitMonth: "90,000 次",
        limit5hCount: 6000,
        limitWeekCount: 45000,
        limitMonthCount: 90000,
        notes: "第三月起¥200/月, 控制台一键切换模型",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "Cline", "Cursor", "OpenClaw"],
    toolCount: 4,
    tags: ["多模型", "首月优惠", "次月半价"],
  },
  {
    id: "moorethreads",
    company: "摩尔线程",
    product: "AI Coding Plan",
    category: "其他",
    links: { official: "https://code.mthreads.com" },
    logo: { src: "/logos/moorethreads.png", alt: "摩尔线程" },
    models: ["GLM-4.7"],
    tiers: [
      {
        name: "Free Trial",
        price: 0,
        period: "月",
        limit5h: "与 Lite 相当",
        isFirstMonthOnly: true,
        notes: "30天免费体验",
      },
      {
        name: "Lite（季付）",
        price: 120,
        period: "季",
        limit5h: "Claude Pro 3倍用量",
        notes: "月均¥40",
      },
      {
        name: "Pro（季付）",
        price: 600,
        period: "季",
        limit5h: "Lite 5倍",
        notes: "月均¥200",
      },
      {
        name: "Max（季付）",
        price: 1200,
        period: "季",
        limit5h: "Pro 4倍, 峰值优先",
        notes: "月均¥400",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code"],
    toolCount: 1,
    tags: ["季度付费", "免费体验"],
  },
  {
    id: "kuaishou",
    company: "快手",
    product: "KwaiKAT Coding Plan",
    category: "其他",
    links: {
      official: "https://www.streamlake.com/marketing/coding-plan",
      affiliate: "https://www.streamlake.com/marketing/cny-model-guess?inviteCode=PR4H9M",
    },
    logo: { src: "/logos/kuaishou.png", alt: "快手" },
    models: [
      "KAT-Coder-Pro-V1",
      "DeepSeek-V3.2",
      "GLM-5",
      "GLM-4.7-Flash",
      "GLM-4.7",
      "MiniMax-M2.5",
      "MiniMax-M2.1-Lightning",
      "MiniMax-M2.1",
      "Kimi-K2.5",
      "Kimi-K2-Thinking",
      "Qwen3-Coder-Next",
      "Qwen3.5-Plus",
      "Qwen3.5-397B-A17B",
    ],
    tiers: [
      {
        name: "Mini",
        price: 29,
        firstMonthPrice: 8.8,
        secondMonthPrice: 29,
        period: "月",
        limit5h: "40 次对话",
        notes: "首月优惠仅限1次；限时特惠期：2026-01-05~2026-03-22",
      },
      {
        name: "Starter",
        price: 70,
        firstMonthPrice: 48,
        secondMonthPrice: 70,
        period: "月",
        limit5h: "100 次对话",
        notes: "首月优惠仅限1次；限时特惠期：2026-01-05~2026-03-22",
      },
      {
        name: "Pro",
        price: 140,
        firstMonthPrice: 96,
        secondMonthPrice: 140,
        period: "月",
        limit5h: "300 次对话",
        notes: "首月优惠仅限1次；限时特惠期：2026-01-05~2026-03-22",
      },
      {
        name: "Max",
        price: 350,
        firstMonthPrice: 240,
        secondMonthPrice: 350,
        period: "月",
        limit5h: "1,000 次对话",
        notes: "首月优惠仅限1次；限时特惠期：2026-01-05~2026-03-22",
      },
    ],
    billingUnit: "请求次数",
    tools: ["Claude Code"],
    toolCount: 1,
    tags: ["多模型", "首月优惠", "限时特惠"],
  },
  {
    id: "ucloud",
    company: "UCloud 优刻得",
    product: "优云智算 Coding Plan",
    category: "国内大厂",
    links: {
      official: "https://www.compshare.cn/coding-plan",
      affiliate: "https://passport.compshare.cn/register?referral_code=7KuMSzfdofaEKUvaTYql35",
    },
    logo: { src: "/logos/ucloud.png", alt: "UCloud" },
    models: [
      "MiniMax-M2.1", "MiniMax-M2.5",
      "claude-haiku-4-5", "claude-sonnet-4-5", "claude-sonnet-4-6", "claude-opus-4-5", "claude-opus-4-6",
      "DeepSeek-V3.2",
      "gpt-5.1", "gpt-5.1-codex-mini", "gpt-5.1-codex-max", "gpt-5.2", "gpt-5.2-codex", "gpt-5.3-codex", "gpt-5.4",
      "Kimi-K2.5", "GLM-5",
    ],
    tiers: [
      {
        name: "超值体验包",
        price: 6.9,
        firstMonthPrice: 6.9,
        period: "包",
        limit5h: "2900万积分",
        isFirstMonthOnly: true,
        notes: "新人专享；面向模型体验及个人日常使用；按量计费，有效期30天（限购一份）",
      },
      {
        name: "标准按量包 Lite",
        price: 19.9,
        period: "包",
        limit5h: "5900万积分",
        notes: "面向个人日常使用；按量计费，有效期180天",
      },
      {
        name: "标准按量包 Plus",
        price: 199,
        period: "包",
        limit5h: "5.9亿积分",
        notes: "面向管理轻量级工作负载的入门级开发人员；按量计费，有效期180天",
      },
      {
        name: "包月畅享包 Lite",
        price: 49.9,
        period: "月",
        limit5h: "每日700万积分",
        limitMonth: "约2.1亿积分",
        notes: "面向日常低频使用；包月，有效期30天；每日0点刷新额度",
      },
      {
        name: "包月畅享包 Plus",
        price: 199,
        period: "月",
        limit5h: "每日2800万积分",
        limitMonth: "约8.4亿积分",
        notes: "面向管理轻量级工作负载的入门级开发人员；包月，有效期30天；每日0点刷新额度",
      },
      {
        name: "包月畅享包 Pro",
        price: 499,
        period: "月",
        limit5h: "每日7000万积分",
        limitMonth: "约21亿积分",
        notes: "面向管理复杂工作负载的专业开发人员；包月，有效期30天；每日0点刷新额度",
      },
    ],
    billingUnit: "积分制",
    tools: ["Claude Code", "OpenClaw", "主流编程工具兼容"],
    toolCount: 5,
    tags: ["最低价", "多模型", "新人专享"],
  },
  {
    id: "cucloud",
    company: "联通云",
    product: "Coding Plan",
    category: "其他",
    links: { official: "https://www.cucloud.cn/activity/kickoffseason.html" },
    logo: { src: "/logos/cucloud.png", alt: "联通云" },
    models: ["GLM-5", "MiniMax-M2.5", "Qwen3.5", "DeepSeek-V3.x"],
    tiers: [
      {
        name: "Lite",
        price: 40,
        firstMonthPrice: 0,
        period: "月",
        limit5h: "18,000 次",
        limitMonth: "18,000 次",
        limitMonthCount: 18000,
        notes: "公测限量免费",
      },
      {
        name: "Pro",
        price: 200,
        firstMonthPrice: 0,
        period: "月",
        limit5h: "90,000 次",
        limitMonth: "90,000 次",
        limitMonthCount: 90000,
        notes: "公测限量免费",
      },
    ],
    billingUnit: "API请求",
    tools: ["Claude Code", "Cursor", "主流编程工具"],
    toolCount: 5,
    tags: ["公测免费", "多模型"],
  },
]
